name: rmg_env
channels:
  - defaults
  - rmg
dependencies:
  - libgcc # [unix]
  - python
  - numpy >=1.10.0
  - cantera >=2.3.0a3
  - coolprop
  - cython >=0.25.2
  - matplotlib >=1.5
  - rdkit >=2015.09.2
  - pydas >=1.0.1
  - pydqed >=1.0.0
  - lpsolve55
  - quantities
  - scipy
  - xlwt
  - markupsafe
  - jinja2
  #- argparse # [py26]
  - pyparsing
  - pydot ==1.2.2
  - pyrdl
  - nose
  - coverage
  - gprof2dot
  - cairo
  - cairocffi
  - openbabel
  - psutil
  - symmetry
  - mopac
  - graphviz
  - scoop
  - ffmpeg
  - jupyter
  - networkx
  - mock
  # - muq
  - pymongo
  - mpmath
  - dde
