name: rmg_env
channels:
  - rmg
  - defaults
dependencies:
  - mingwpy
  - python
  - numpy >=1.10.0
  - cantera >=2.3.0a3
  - coolprop
  - cython >=0.25.2
  - matplotlib >=1.5
  - rdkit >=2015.09.2
  - lpsolve55
  - quantities
  - scipy
  - xlwt
  - markupsafe
  - jinja2
  - pyparsing
  - pydas 
  - pydot ==1.2.2
  - pydqed
  - pyrdl
  - nose
  - coverage
  - gprof2dot
  - cairo
  - cairocffi
  - openbabel
  - psutil
  - symmetry
  - mopac
  - graphviz
  - scoop
  - ffmpeg
  - jupyter
  - networkx
  - mock
  # - muq
  - pymongo
  - mpmath
  - dde
