name: rmg_env
channels:
  - defaults
  - rmg
  - rdkit
  - cantera
  - anaconda
dependencies:
  - cairo
  - cairocffi
  - cantera >=2.3.0
  - coincbc
  - coolprop
  - coverage
  - cython >=0.25.2
  - dde
  - ffmpeg
  - glpk
  - gprof2dot
  - graphviz
  - jinja2
  - jupyter
  - lpsolve55
  - markupsafe
  - matplotlib >=1.5
  - mingwpy
  - mock
  - mopac
  - mpmath
#  - muq
  - networkx
  - nose
  - numpy >=1.10.0
  - openbabel
  - psutil
  - pydas >=1.0.1
  - pydot ==1.2.2
  - pydot-ng
  - pydqed >=1.0.0
  - pygpu
  - pymongo
  - pyomo
  - pyparsing
  - pyrdl
  - python >=2.7
  - pyyaml
  - quantities
  - rdkit >=2018
  - scikit-learn
  - scipy
  - symmetry
  - textgenrnn
  - xlwt
